export interface BonusAuditListItem {
  [key: string]: unknown;
  Amount?: number | string;
  Approve?: number;
  ApproveName?: string;
  ApproveRemark?: string;
  ApproveTime?: number | string;
  ChannelId?: number | string;
  ChannelName?: string;
  CreateAdminId?: number | string;
  CreateTime?: number | string;
  HandleDesc?: string;
  HandlerName?: string;
  Id?: number | string;
  LoginAccount?: string;
  OrderId?: string;
  PackageName?: string;
  PageTitle?: string;
  PageType?: number;
  PlayerId?: number | string;
  PlayerStatus?: number;
  RealApplyAmount?: number | string;
  Reason?: number;
  Title?: string;
  VipLevel?: number | string;
  Water?: number | string;
  WaterAmount?: number | string;
  WaterType?: number;
}

export interface BonusRecordListItem {
  [key: string]: unknown;
  Account?: string;
  ActivityType?: number | string;
  Amount?: number | string;
  ApplyAccount?: string;
  ApplyNote?: string;
  ApplyTime?: number | string;
  Bonus?: number | string;
  BonusTitle?: string;
  BonusType?: number | string;
  CreateTime?: number | string;
  Draw?: number | string;
  FailTime?: number | string;
  FinishTime?: number | string;
  FirstPayTime?: number | string;
  IsWater?: number | string;
  LoginAccount?: string;
  Operator?: string;
  OrderId?: string;
  PackageName?: string;
  PageTitle?: string;
  PageType?: number | string;
  PlayerId?: number | string;
  PlayerStatus?: number | string;
  Reason?: number | string;
  RegisterTime?: number | string;
  ReviewNote?: string;
  SendType?: number | string;
  Status?: number | string;
  Title?: string;
  Username?: string;
  VipLevel?: number | string;
  WaterAmount?: number | string;
  WaterReward?: number | string;
  WaterType?: number | string;
}

export interface BonusAuditListQuery {
  ActivityType?: number;
  ApplyBeginTime?: number | string;
  ApplyEndTime?: number | string;
  Approve?: number | string;
  ApproveBeginTime?: number | string;
  ApproveEndTime?: number | string;
  ApproveStatus?: number | string;
  AppUrl?: string;
  BeginTime?: number | string;
  BonusTitle?: string;
  BonusType?: Array<number | string> | number | string;
  ChannelIds?: Array<number | string> | number | string;
  EndTime?: number | string;
  FinishBeginTime?: number | string;
  FinishEndTime?: number | string;
  IsExp?: boolean;
  IsWater?: number | string;
  LoginAccount?: string;
  OperatorAccount?: string;
  OperatorAccountType?: number;
  OperatorRemark?: string;
  OperatorRemarkType?: number;
  OrderId?: string;
  PackageId?: number | string;
  PackageName?: string;
  Page: number;
  PageSize: number;
  PageTitle?: string;
  PageType?: number | string;
  PlayerStatus?: number | string;
  Reason?: number | string;
  RiskStatus?: number | string;
  SendType?: number | string;
  Status?: number | string;
  Title?: string;
  Username?: string;
  VipLevel?: number | string;
  WaterType?: number;
}
