/** 安全管理 PageId（对照 SECURITY_PATHS / 旧站 GoogleCode） */
export const DOWNLOAD_CSV_SECURITY_PAGE_ID = 17;
export const WITHDRAW_RISK_SECURITY_PAGE_ID = 26;
export const MEMBER_LOGIN_EXPORT_PAGE_ID = 34;
export const GAME_RECORD_EXPORT_PAGE_ID = 35;
export const WITHDRAW_REDEEM_EXPORT_PAGE_ID = 37;
export const WITHDRAW_FINANCE_EXPORT_PAGE_ID = 38;
export const ACCOUNT_ADJUST_AUDIT_PAGE_ID = 49;
export const REWARD_POINT_ADJUST_AUDIT_PAGE_ID = 83;
export const REWARD_EXCHANGE_EXPORT_PAGE_ID = 82;
export const REWARD_POINT_RECORD_EXPORT_PAGE_ID = 84;
export const AUTH_RECORD_EXPORT_PAGE_ID = 90;
export const EVO_SIDEBET_EXPORT_PAGE_ID = 95;
export const VOUCHER_DETAIL_RECORD_EXPORT_PAGE_ID = 86;
export const LEADERBOARD_RECORD_EXPORT_PAGE_ID = 87;
export const VOUCHER_ISSUE_RECORD_EXPORT_PAGE_ID = 88;
export const RELATION_QUERY_EXPORT_PAGE_ID = 91;
export const VISIT_STATISTIC_EXPORT_PAGE_ID = 33;
export const PLAYER_LIST_EXPORT_PAGE_ID = 32;
/** 称号拥有者列表导出 */
export const GAME_TITLE_OWNER_EXPORT_PAGE_ID = 75;
